### ISSUE TITLE
about spring.jpa.template-location

### ISSUE THREAD

**Issue by yummykang** [slyak/spring-data-jpa-extra#1]
${spring.jpa.template-location:classpath:/sqls} 
does it can use wildcard, sometimes there would be several model.

**Comment by stormning** [comment]
ok i'll consider that later , thank you for your advice!

**Comment by stormning** [comment]
This style will be supported in version 1.1.0
spring.jpa.template-location = classpath:**/**Sql.xml
thank you for your advice!
