### ISSUE TITLE
Template not found for name XXX

### ISSUE THREAD

**Issue by rplees** [slyak/spring-data-jpa-extra#15]
FreemarkerTemplateQuery.getEntityName ->(User)跟 FreemarkerSqlTemplates.em.getMetamodel().getEntities().getName() -> (t_user)不是同一个,造成找不到自定义ftl文件

**Comment by stormning** [comment]
请查看 https://github.com/slyak/spring-data-jpa-extra/issues/11

**Comment by stormning** [comment]
相同的问题，我关闭了

**Comment by rplees** [comment]
@stormning 明白, 

补充下,你刚才说的 "Entity命名了,模板要跟Entity名一致(t_user, t_user.sftl)",是有问题的,因为FreemarkerTemplateQuery.getEntityName是getJavaType().getSimpleName()获取类的名字,还是会无法找到User.xxxx .

**Comment by stormning** [comment]
嗯，谢谢提醒。
我后面会修改成和Entity名一致的逻辑，防止类名一致发生冲突
