### ISSUE TITLE
能否支持List<Map>的返回值，就是没有实体对象的查询

### ISSUE THREAD

**Issue by 1013785085** [slyak/spring-data-jpa-extra#17]

**Comment by stormning** [comment]
@1013785085 您好，很高兴能收到您的建议，刚发布了一个小版本2.1.2.RELEASE，增加了对List<Map>对支持，稍后可以试一下，估计同步到中央仓库需要那么一小段时间

**Comment by 1013785085** [comment]
响应速度有点快👍，spring5是不是不支持？我用spring5无法读取自定义的SQL

**Comment by stormning** [comment]
@1013785085 spring5还没测试过，因为spring-boot 2.0还没release
我一会测试下兼容性
