### ISSUE TITLE
项目中使用freemarker会和你这个freemarker缓存冲突，你的项目中会重置TemplateLoader对象

### ISSUE THREAD

**Issue by 1013785085** [slyak/spring-data-jpa-extra#19]

**Comment by stormning** [comment]
不存在冲突吧，FreemarkerSqlTemplates对象中的templateLoader是方法内部的成员变量，并没有初始化到spring的上下文里。不太理解您所说的冲突在哪里？

**Comment by 1013785085** [comment]
现在的问题是如果我的程序先加载应用页面的模板就会找不到你的项目的模板，如果先加载你的项目模板就会找不到应用页面的模板，而且跟踪加载应用页面模板调试发现缓存中只有你的项目模板缓存

**Comment by stormning** [comment]
应该不会啊，因为我也用了spring-boot的freemarker的view的模板，并没有出现冲突。
你能把出问题的代码发给我或者放github上，我可以帮你找找是什么原因

**Comment by 1013785085** [comment]
https://gitee.com/0A0/SuiYi,这个是我的代码，请帮忙检查是不是配置问题谢谢

**Comment by stormning** [comment]
@1013785085 访问不了，是不是没有加权限，我账号stormning

**Comment by 1013785085** [comment]
已经你添加为管理员，你看看你能不能访问，我项目设置的为公开的，我在不登陆的状态是可以下载的

**Comment by 1013785085** [comment]
已经解决
