### ISSUE TITLE
found duplicate template key, will replace the value

### ISSUE THREAD

**Issue by xiehonghpu** [slyak/spring-data-jpa-extra#37]
![image](https://user-images.githubusercontent.com/8263127/47557120-83f8f500-d942-11e8-91a7-4b8f54bd7f48.png)

template key是唯一的，并且target下也只有一个该名称的.sftl文件，但是会提示重复。spring-data-jpa-extra版本号：2.1.1.RELEASE

**Comment by xiehonghpu** [comment]
会打印warn语句，提示会replace语句，这个算正常吗？

**Comment by stormning** [comment]
template查找支持两种方式：
文件放置位置方式templateLocation，默认classpath:/sqls
包路径方式templateBasePackage，默认/**/*.sftl
这两种方式支持同时存在。
如果，这个参数你设置重叠了，会出现这个现象

**Comment by xiehonghpu** [comment]
@stormning 确实是这样，下个版本修复吗？

**Comment by stormning** [comment]
这个没问题，两种方式都支持，这个warn只是提示并让你确认一下是否你要同时采用这两种方式。一般情况你只要配置一种即可。
