### ISSUE TITLE
希望能够把3.0的版本提交到maven仓库

### ISSUE THREAD

**Issue by jy05568536** [slyak/spring-data-jpa-extra#39]

**Comment by bashuyi** [comment]
麻烦作者提交3.0版，下载了3.0版和父工程2.0版到本地编译报错，现在没法在SpringBoot2中使用这个框架，启动提示No property XXX found for type XXX!错误

**Comment by bashuyi** [comment]
我已经把3.0版本提交到了jitpack，如果哪位遇到了同样的问题可以使用，免去踩同样的坑。最后谢谢作者提供了这么好用的框架。
	<repositories>
		<repository>
		    <id>jitpack.io</id>
		    <url>https://jitpack.io</url>
		</repository>
	</repositories>

	<dependency>
	    <groupId>com.github.bashuyi</groupId>
	    <artifactId>spring-data-jpa-extra</artifactId>
	    <version>3.0.0-SNAPSHOT</version>
	</dependency>

**Comment by stormning** [comment]
非常感谢，最近比较忙，一直没有时间来发布新版本。

**Comment by jy05568536** [comment]
非常感谢

**Comment by stormning** [comment]
OK，刚才已经将3.0.0.RELEASE发布到中央仓库，估计过一会就可以下载到了
