### ISSUE TITLE
会有sql注入的问题吗？

### ISSUE THREAD

**Issue by someorz** [slyak/spring-data-jpa-extra#4]
有没有做sql注入的验证

**Comment by stormning** [comment]
不会有，只要你用:paramName的方式，这种是prepareStatement的，如果你使用过hibernate的:paramName话，就明白了

**Comment by halower** [comment]
如果是if 等动态指令传参避免不了注入啊，但是如果不使用freemarker指令，又怎么动态

**Comment by stormning** [comment]
用冒号做占位（preparedstatment），不要用字符串相加，这个是常识性问题。

**Comment by stormning** [comment]
if 用作条件判断，变量用 :paramName, 不要用字符串拼接就不会有问题
