### ISSUE TITLE
为什么不把SQL直接写在@TemplateQuery注解上呢？

### ISSUE THREAD

**Issue by gbguanbo** [slyak/spring-data-jpa-extra#43]
这样既可以避免方法名相同的问题，也无须再开发过程中切换
![image](https://user-images.githubusercontent.com/804801/53386327-b41dd680-39bc-11e9-8140-ae880e81b28e.png)
![image](https://user-images.githubusercontent.com/804801/53386361-dc0d3a00-39bc-11e9-8d0d-6fea8f22d95e.png)

**Comment by stormning** [comment]
是为复杂SQL设计的，复杂查询一般有很多行，写代码里看起来不方便，一般简单的原生就可以搞定了。

**Comment by cheng6563** [comment]
你真的觉得这种多行字符串很好看吗？
