### ISSUE TITLE
查询参数可以使用Map<String, Object>吗

### ISSUE THREAD

**Issue by bashuyi** [slyak/spring-data-jpa-extra#44]
我想动态的传递参数，请问可以使用Map<String, Object>吗

**Comment by stormning** [comment]
可以用个object（如 UserQuery），map我忘了可不可以了...

**Comment by bashuyi** [comment]
用Map报异常。org.springframework.dao.InvalidDataAccessApiUsageException: Query must not be null or empty!; nested exception is java.lang.IllegalArgumentException: Query must not be null or empty!

**Comment by doufuplus** [comment]
为什么我加了@TemplateQuery注解后依旧报错：
Caused by: org.springframework.data.mapping.PropertyReferenceException: No property xxx found for type xxx!

**Comment by bashuyi** [comment]
已经解决。直接只传Map类型的参数，可以动态传递查询条件。之前同时传map和字符串类型参数，字符串类型参数会被map覆盖，所以报错。
