### ISSUE TITLE
Oracle 12c  SQL 命令未正确结束

### ISSUE THREAD

**Issue by tangrongwei** [slyak/spring-data-jpa-extra#48]
select count(*) from (select black_reason,tb.id,tb.project_code,tp.project_name,remark,tb.sub_contractor_code,ts.sub_contractor_name,black_or_write from t_subcontractorblacklist tb inner join t_projectmaster tp on tp.project_code = tb.project_code inner join t_projectsubcontractor ts on ts.sub_contractor_code=tb.sub_contractor_code where tp.project_code = ts.project_code    ) as ctmp

自动生成上述语句，Oracle不支持，请问有解决方式吗

**Comment by stormning** [comment]
最近在忙AI的事情，无暇顾及，等过一阵子有空了，完善一下，我估计就是alias这些问题

**Comment by tangrongwei** [comment]
辛苦辛苦
