### ISSUE TITLE
出现一个问题，stfl文件中的if条件没起作用，if中的语句没有拼接到sql上

### ISSUE THREAD

**Issue by myfairys** [slyak/spring-data-jpa-extra#53]
--findDtos
SELECT id, name FROM zk_user where 1=1 <#if (name??)>
   AND name like :name
</#if>

Hibernate: 
    /* dynamic native SQL query */ SELECT
        id,
        name 
    FROM
        zk_user 
    where
        1=1
没有拼接name条件语句

**Comment by stormning** [comment]
<#if name??>

**Comment by stormning** [comment]
注意接口中，name前面要加注解 @Param
