### ISSUE TITLE
Database connection pool leaking

### ISSUE THREAD

**Issue by onlychan** [slyak/spring-data-jpa-extra#6]
I found that the database connection pool leaking in use with sftl file,
However the direct use of annotation such as  '@ Query' doesn't have this problem,
So I need something for help.  @stormning

**Comment by stormning** [comment]
please use
if you are using spring-boot, please set spring.jpa.open-in-view=true
otherwise setup  org.springframework.orm.jpa.support.OpenEntityManagerInViewFilter

this is the same issue: https://github.com/slyak/spring-data-jpa-extra/issues/2
