### ISSUE TITLE
Blob or Clob mapping error

### ISSUE THREAD

**Issue by onlychan** [slyak/spring-data-jpa-extra#7]
In the process of using this SQL template,
We found that the ResultSet with byte[] mapped by Blob or String mapped by Clob might cause errors,
Is there a solution to solve?

**Comment by onlychan** [comment]
@stormning

**Comment by stormning** [comment]
@onlychan ok，I'll take a look at it，thank you for your advice.

**Comment by onlychan** [comment]
I found that the function body QueryBuilder.cleanOrderBy(String query) will return an empty string when I use a query without 'order by'. Is this the program bug, or the original design? @stormning

**Comment by stormning** [comment]
@onlychan 
Put up your sql , please .

**Comment by onlychan** [comment]
```
String t1 = "select * from user";
System.out.println(QueryBuilder.toCountQuery(t1));
```
It will print message “select count(*) ctmp” on the console. @stormning

**Comment by onlychan** [comment]
String t1 = "select * from user";
System.out.println(QueryBuilder.toCountQuery(t1));
It will print message “select count(*) from () ctmp” on the console. @stormning

**Comment by onlychan** [comment]
```
String t1 = "select * from user";
System.out.println(QueryBuilder.toCountQuery(t1));
```
It will print message

>  “select count(*) from () ctmp” 

on the console. 
@stormning

**Comment by onlychan** [comment]
```
String t1 = "select * from user";
System.out.println(QueryBuilder.toCountQuery(t1));
```
It will print message on console like this:

> select count(*) from () ctmp
@stormning

**Comment by onlychan** [comment]
@stormning 
```
String t1 = "select * from user";
System.out.println(QueryBuilder.toCountQuery(t1));
```
It will print message on console like this:

> select count(*) from () ctmp

**Comment by stormning** [comment]
please use the latest version 2.0.3.RELEASE

**Comment by stormning** [comment]
fixed in master branch
